#!/usr/bin/env bash
#A script that installs nginx on your sever and run on your server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
service nginx start
