#!/usr/bin/env bash
#To configure Nginx so that HTTP response contains a custom header
#(on web-01 and web-02).The name of the custom HTTP header is X-Served-By
var=$(hostname)
new_string="error_page 404 \/custon_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
new_string2="server {\n\tadd_header X-served-By $var;"

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /usr/share/nginx/html/index.html
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default
sudo service nginx start
