#!/usr/bin/env bash
# This is a Bash script that displays listening ports:
# Also that only shows listening sockets
# Also that shows the PID and name of the program to which each socket belongs

sudo netstat -lp
