#!/usr/bin/env bash
#Ths script displays "Best School" 10 times but and the 9th iteration,
#displays "Hi" on a new line
i=1
while [ $i -le 10 ]
do
	echo "Best School"
	if [ $i -eq 9 ]; then
	   echo "Hi"
	fi
	i=$((i+1))
done
