#!/usr/bin/env bash
# A script to update Nginx configuration to run as the nginx user

systemctl stop nginx

sed -i 's/user  nginx;/user nginx nginx;/' /etc/nginx/nginx.conf

sed -i "s/80/8080/g" /etc/nginx/sites-available/default

systemctl start nginx
