#!/usr/bin/env bash
# A script to update Nginx configuration to run as the nginx user

sed -i 's/user  nginx;/user  nginx;/' /etc/nginx/nginx.conf
cat > /etc/nginx/conf.d/default.conf <<EOL
server {
   listen      8080 default_server;
   server_name -;

   location / {
       root     /usr/share/nginx/html;
       index    index.html;
   }
}
EOL

nginx -g "daemon off;"      

