#!/usr/bin/env bash
# A script to update Nginx configuration to run as the nginx user

sed -i 's/user  nginx;/user  nginx;/' /etc/nginx/nginx.conf
echo 'server {
    listen *:8080 default_server;
    server_name  _;
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }
}' > sudo tee /etc/nginx/conf.d/default.conf

service nginx restart
