#!/usr/bin/env bash
#Script that uses ssh to connect to your server using the private
#key ~/.ssh/school with the user ubuntu
server_address="your_server_ip_or_hostname"
private_key="~/.ssh/school"
remote_user="ubuntu"

ssh-i ~/.ssh/school ubuntu@34.224.62.116
